version: '3.1'
services:
  redis:
    image: redis:latest
    container_name: rd01

  webapp:
    build: .
    container_name: wa01
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - mynetwork

  celery:
    build: .
    volumes:
      - .:/src
    container_name: cl01
    command: celery -A checkGenApp worker -l info
    depends_on:
      - redis
    networks:
      - mynetwork

networks:
  mynetwork:
